

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      # - "443:443"   # enable if SSL
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./app:/usr/share/nginx/html:ro   # if serving static files
    depends_on:
      - app
    networks:
      - net
      
db:
  image: postgres
  container_name: postgres_db
  restart: always
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: myuser
    POSTGRES_PASSWORD: mypassword
    POSTGRES_DB: mydatabase
  volumes:
    - db_data:/var/lib/postgresql/data
  networks:
    - net

volumes:
  db_data:

networks:
  net:
    driver: bridge