"""empty message

Revision ID: 6b4abd41b7d5
Revises: 79fa01533411
Create Date: 2025-10-03 14:38:14.287659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4abd41b7d5'
down_revision: Union[str, Sequence[str], None] = '79fa01533411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_tag', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'user', ['user_tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_tag')
    # ### end Alembic commands ###
