"""empty message

Revision ID: ce364bcf1562
Revises: 6b4abd41b7d5
Create Date: 2025-10-07 19:56:10.150443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce364bcf1562'
down_revision: Union[str, Sequence[str], None] = '6b4abd41b7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_type', sa.String(), nullable=True))
    op.add_column('message', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('message', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('message', sa.Column('file_type', sa.String(), nullable=True))
    op.add_column('message', sa.Column('file_size', sa.Integer(), nullable=True))
    op.alter_column('message', 'text',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'text',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
    op.drop_column('message', 'file_size')
    op.drop_column('message', 'file_type')
    op.drop_column('message', 'file_name')
    op.drop_column('message', 'file_url')
    op.drop_column('message', 'message_type')
    # ### end Alembic commands ###
